# Generated by Django 4.2.16 on 2024-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='cat'),
            preserve_default=False,
        ),
    ]
