# Generated by Django 4.2.16 on 2024-10-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
