# Generated by Django 5.1.1 on 2024-10-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
