# Generated by Django 4.2.16 on 2024-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
