# Generated by Django 4.2.16 on 2024-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name_ka',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name_ka',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
